-- Snapshot dos dados locais inclu?do na primeira publica??o.
INSERT OR IGNORE INTO "Setor" ("id", "nome", "ordemPadrao", "createdAt", "updatedAt", "lider", "metaMensal", "diasUteisMes") VALUES (1, 'SOLDA', 7, 1783874060918, 1784497156144, 'PETRUS', 1200, 22);
INSERT OR IGNORE INTO "Setor" ("id", "nome", "ordemPadrao", "createdAt", "updatedAt", "lider", "metaMensal", "diasUteisMes") VALUES (2, 'TUBO', 1, 1783874071152, 1783879279055, 'CARLOS', 600, 22);
INSERT OR IGNORE INTO "Setor" ("id", "nome", "ordemPadrao", "createdAt", "updatedAt", "lider", "metaMensal", "diasUteisMes") VALUES (3, 'PLASMA CHAPA', 3, 1783874080599, 1783879279097, 'CAIO', 800, 22);
INSERT OR IGNORE INTO "Setor" ("id", "nome", "ordemPadrao", "createdAt", "updatedAt", "lider", "metaMensal", "diasUteisMes") VALUES (4, 'PLASMA TUBO', 2, 1783874084598, 1783879279077, 'ALAN', 700, 22);
INSERT OR IGNORE INTO "Setor" ("id", "nome", "ordemPadrao", "createdAt", "updatedAt", "lider", "metaMensal", "diasUteisMes") VALUES (5, 'COMPONENTES E ACESSÓRIOS', 4, 1783874087262, 1783879279115, 'ANDRE', 900, 22);
INSERT OR IGNORE INTO "Setor" ("id", "nome", "ordemPadrao", "createdAt", "updatedAt", "lider", "metaMensal", "diasUteisMes") VALUES (6, 'MONTAGEM', 9, 1783874089759, 1783879279200, 'FELIPE', 1400, 22);
INSERT OR IGNORE INTO "Setor" ("id", "nome", "ordemPadrao", "createdAt", "updatedAt", "lider", "metaMensal", "diasUteisMes") VALUES (7, 'PINTURA', 8, 1783874091144, 1783879279181, 'DANIEL', 1300, 22);
INSERT OR IGNORE INTO "Setor" ("id", "nome", "ordemPadrao", "createdAt", "updatedAt", "lider", "metaMensal", "diasUteisMes") VALUES (8, 'PONTEIRA', 5, 1783874094884, 1783879279134, 'ALEX', 1000, 22);
INSERT OR IGNORE INTO "Setor" ("id", "nome", "ordemPadrao", "createdAt", "updatedAt", "lider", "metaMensal", "diasUteisMes") VALUES (9, 'AGRUPAMENTO', 6, 1783879279138, 1783879279154, 'ANA', 1100, 22);
INSERT OR IGNORE INTO "Funcionario" ("id", "nome", "setorId", "ativo", "pin", "papel", "createdAt", "updatedAt") VALUES (2, 'PEDRO', 1, 1, NULL, 'OPERADOR', 1783874125431, 1783874125431);
INSERT OR IGNORE INTO "Funcionario" ("id", "nome", "setorId", "ativo", "pin", "papel", "createdAt", "updatedAt") VALUES (3, 'ANTONIO', 1, 1, NULL, 'OPERADOR', 1783874133119, 1783874133119);
INSERT OR IGNORE INTO "Funcionario" ("id", "nome", "setorId", "ativo", "pin", "papel", "createdAt", "updatedAt") VALUES (4, 'MARIO', 1, 1, NULL, 'OPERADOR', 1783874137951, 1783874137951);
INSERT OR IGNORE INTO "Funcionario" ("id", "nome", "setorId", "ativo", "pin", "papel", "createdAt", "updatedAt") VALUES (5, 'CARLOS', 2, 1, '1234', 'LIDER', 1783879279040, 1784500571761);
INSERT OR IGNORE INTO "Funcionario" ("id", "nome", "setorId", "ativo", "pin", "papel", "createdAt", "updatedAt") VALUES (6, 'JOAO', 2, 1, '5678', 'OPERADOR', 1783879279043, 1784500530784);
INSERT OR IGNORE INTO "Funcionario" ("id", "nome", "setorId", "ativo", "pin", "papel", "createdAt", "updatedAt") VALUES (7, 'MARCOS', 2, 1, NULL, 'OPERADOR', 1783879279047, 1783879279047);
INSERT OR IGNORE INTO "Funcionario" ("id", "nome", "setorId", "ativo", "pin", "papel", "createdAt", "updatedAt") VALUES (8, 'RAFAEL', 2, 1, NULL, 'OPERADOR', 1783879279051, 1783879279051);
INSERT OR IGNORE INTO "Funcionario" ("id", "nome", "setorId", "ativo", "pin", "papel", "createdAt", "updatedAt") VALUES (9, 'ALAN', 4, 1, NULL, 'OPERADOR', 1783879279062, 1783879279062);
INSERT OR IGNORE INTO "Funcionario" ("id", "nome", "setorId", "ativo", "pin", "papel", "createdAt", "updatedAt") VALUES (10, 'BRUNO', 4, 1, NULL, 'OPERADOR', 1783879279066, 1783879279066);
INSERT OR IGNORE INTO "Funcionario" ("id", "nome", "setorId", "ativo", "pin", "papel", "createdAt", "updatedAt") VALUES (11, 'DIEGO', 4, 1, NULL, 'OPERADOR', 1783879279069, 1783879279069);
INSERT OR IGNORE INTO "Funcionario" ("id", "nome", "setorId", "ativo", "pin", "papel", "createdAt", "updatedAt") VALUES (12, 'EVANDRO', 4, 1, NULL, 'OPERADOR', 1783879279073, 1783879279073);
INSERT OR IGNORE INTO "Funcionario" ("id", "nome", "setorId", "ativo", "pin", "papel", "createdAt", "updatedAt") VALUES (13, 'CAIO', 3, 1, NULL, 'OPERADOR', 1783879279084, 1783879279084);
INSERT OR IGNORE INTO "Funcionario" ("id", "nome", "setorId", "ativo", "pin", "papel", "createdAt", "updatedAt") VALUES (14, 'FABIO', 3, 1, NULL, 'OPERADOR', 1783879279087, 1783879279087);
INSERT OR IGNORE INTO "Funcionario" ("id", "nome", "setorId", "ativo", "pin", "papel", "createdAt", "updatedAt") VALUES (15, 'GILBERTO', 3, 1, NULL, 'OPERADOR', 1783879279091, 1783879279091);
INSERT OR IGNORE INTO "Funcionario" ("id", "nome", "setorId", "ativo", "pin", "papel", "createdAt", "updatedAt") VALUES (16, 'LEANDRO', 3, 1, NULL, 'OPERADOR', 1783879279094, 1783879279094);
INSERT OR IGNORE INTO "Funcionario" ("id", "nome", "setorId", "ativo", "pin", "papel", "createdAt", "updatedAt") VALUES (17, 'ANDRE', 5, 1, NULL, 'OPERADOR', 1783879279103, 1783879279103);
INSERT OR IGNORE INTO "Funcionario" ("id", "nome", "setorId", "ativo", "pin", "papel", "createdAt", "updatedAt") VALUES (18, 'CLEBER', 5, 1, NULL, 'OPERADOR', 1783879279106, 1783879279106);
INSERT OR IGNORE INTO "Funcionario" ("id", "nome", "setorId", "ativo", "pin", "papel", "createdAt", "updatedAt") VALUES (19, 'DOUGLAS', 5, 1, NULL, 'OPERADOR', 1783879279109, 1783879279109);
INSERT OR IGNORE INTO "Funcionario" ("id", "nome", "setorId", "ativo", "pin", "papel", "createdAt", "updatedAt") VALUES (20, 'RENATO', 5, 1, NULL, 'OPERADOR', 1783879279112, 1783879279112);
INSERT OR IGNORE INTO "Funcionario" ("id", "nome", "setorId", "ativo", "pin", "papel", "createdAt", "updatedAt") VALUES (21, 'ALEX', 8, 1, NULL, 'OPERADOR', 1783879279122, 1783879279122);
INSERT OR IGNORE INTO "Funcionario" ("id", "nome", "setorId", "ativo", "pin", "papel", "createdAt", "updatedAt") VALUES (22, 'EDUARDO', 8, 1, NULL, 'OPERADOR', 1783879279125, 1783879279125);
INSERT OR IGNORE INTO "Funcionario" ("id", "nome", "setorId", "ativo", "pin", "papel", "createdAt", "updatedAt") VALUES (23, 'HUGO', 8, 1, NULL, 'OPERADOR', 1783879279128, 1783879279128);
INSERT OR IGNORE INTO "Funcionario" ("id", "nome", "setorId", "ativo", "pin", "papel", "createdAt", "updatedAt") VALUES (24, 'RODRIGO', 8, 1, NULL, 'OPERADOR', 1783879279131, 1783879279131);
INSERT OR IGNORE INTO "Funcionario" ("id", "nome", "setorId", "ativo", "pin", "papel", "createdAt", "updatedAt") VALUES (25, 'ANA', 9, 1, NULL, 'OPERADOR', 1783879279142, 1783879279142);
INSERT OR IGNORE INTO "Funcionario" ("id", "nome", "setorId", "ativo", "pin", "papel", "createdAt", "updatedAt") VALUES (26, 'BRUNA', 9, 1, NULL, 'OPERADOR', 1783879279144, 1783879279144);
INSERT OR IGNORE INTO "Funcionario" ("id", "nome", "setorId", "ativo", "pin", "papel", "createdAt", "updatedAt") VALUES (27, 'LUCAS', 9, 1, NULL, 'OPERADOR', 1783879279147, 1783879279147);
INSERT OR IGNORE INTO "Funcionario" ("id", "nome", "setorId", "ativo", "pin", "papel", "createdAt", "updatedAt") VALUES (28, 'PAULO', 9, 1, NULL, 'OPERADOR', 1783879279151, 1783879279151);
INSERT OR IGNORE INTO "Funcionario" ("id", "nome", "setorId", "ativo", "pin", "papel", "createdAt", "updatedAt") VALUES (29, 'DANIEL', 7, 1, NULL, 'OPERADOR', 1783879279169, 1783879279169);
INSERT OR IGNORE INTO "Funcionario" ("id", "nome", "setorId", "ativo", "pin", "papel", "createdAt", "updatedAt") VALUES (30, 'ELIAS', 7, 1, NULL, 'OPERADOR', 1783879279171, 1783879279171);
INSERT OR IGNORE INTO "Funcionario" ("id", "nome", "setorId", "ativo", "pin", "papel", "createdAt", "updatedAt") VALUES (31, 'MAURICIO', 7, 1, NULL, 'OPERADOR', 1783879279175, 1783879279175);
INSERT OR IGNORE INTO "Funcionario" ("id", "nome", "setorId", "ativo", "pin", "papel", "createdAt", "updatedAt") VALUES (32, 'WESLEY', 7, 1, NULL, 'OPERADOR', 1783879279178, 1783879279178);
INSERT OR IGNORE INTO "Funcionario" ("id", "nome", "setorId", "ativo", "pin", "papel", "createdAt", "updatedAt") VALUES (33, 'FELIPE', 6, 1, NULL, 'OPERADOR', 1783879279188, 1783879279188);
INSERT OR IGNORE INTO "Funcionario" ("id", "nome", "setorId", "ativo", "pin", "papel", "createdAt", "updatedAt") VALUES (34, 'GUSTAVO', 6, 1, NULL, 'OPERADOR', 1783879279191, 1783879279191);
INSERT OR IGNORE INTO "Funcionario" ("id", "nome", "setorId", "ativo", "pin", "papel", "createdAt", "updatedAt") VALUES (35, 'RICARDO', 6, 1, NULL, 'OPERADOR', 1783879279193, 1783879279193);
INSERT OR IGNORE INTO "Funcionario" ("id", "nome", "setorId", "ativo", "pin", "papel", "createdAt", "updatedAt") VALUES (36, 'VINICIUS', 6, 1, NULL, 'OPERADOR', 1783879279196, 1783879279196);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (83, 'AD1001-PL1', 'CORTE PLASMA LADO DIREITO', '6.35 mm', 3, 1784409213942, 1784583939611, NULL, NULL, 6.35, NULL, NULL, 'CHAPA', 'CORTE,DOBRA', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (84, 'AD1001-PL2', 'CORTE PLASMA LADO ESQUERDO', '6.35 mm', 3, 1784409213944, 1784583953538, NULL, NULL, 6.35, NULL, NULL, 'CHAPA', 'CORTE,DOBRA', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (85, 'AD1001-TB', 'TUBO SUPORTE PRINCIPAL', '40 × 40 × 3 mm · comp. 1010 mm', 2, 1784409213945, 1784583968796, NULL, 1010, 3, 40, 40, 'TUBO', 'CORTE,DOBRA,CORTE_GRAU', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (86, 'AD1001-CB', 'PONTEIRA REM.', '60 × 60 × 3.75 mm · comp. 240 mm', 4, 1784409213946, 1784583983244, NULL, 240, 3.75, 60, 60, 'PONTEIRA', 'CORTE', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (87, 'AD1001-RCB', 'REFORÇO DE CABEÇA ENGATE', '75 × 3 mm · comp. 100 mm', 5, 1784409213947, 1784584002193, NULL, 100, 3, 75, NULL, 'REFORCO', 'CORTE', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (88, 'AD1002N-PL1', 'CORTE PLASMA LATERAL ESQUERDA', '6.35 mm', 3, 1784409213949, 1784409213949, NULL, NULL, 6.35, NULL, NULL, 'CHAPA', 'CORTE,DOBRA', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (89, 'AD1002N-PL2', 'CORTE PLASMA LATERAL DIREITA', '6.35 mm', 3, 1784409213950, 1784409213950, NULL, NULL, 6.35, NULL, NULL, 'CHAPA', 'CORTE,DOBRA', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (90, 'AD1002N-PL3', 'CORTE PLASMA CENTRAL', '6.35 mm', 3, 1784409213950, 1784409213950, NULL, NULL, 6.35, NULL, NULL, 'CHAPA', 'CORTE,DOBRA', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (91, 'AD1002N-PL4', 'CORTE PLASMA BICENTRAL', '6.35 mm', 3, 1784409213951, 1784409213951, NULL, NULL, 6.35, NULL, NULL, 'CHAPA', 'CORTE', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (92, 'AD1002N-TB1', 'TUBO SUPORTE PRINCIPAL — RETO', '40 × 40 × 3 mm · comp. 920 mm', 2, 1784409213952, 1784409213952, NULL, 920, 3, 40, 40, 'TUBO', 'CORTE', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (93, 'AD1002N-CB1', 'PONTEIRA REM.', '60 × 60 × 3.75 mm · comp. 250 mm', 4, 1784409213953, 1784479095656, NULL, 250, 3.75, 60, 60, 'PONTEIRA', 'CORTE', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (94, 'AD1002N-REF1', 'REFORÇO DE CABEÇA ENGATE', '100 × 8 mm · comp. 190 mm', 5, 1784409213954, 1784409213954, NULL, 190, 8, 100, NULL, 'REFORCO', 'CORTE,DOBRA', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (95, 'AD1003-PL1', 'CORTE PLASMA LATERAL DIREITA', NULL, 3, 1784409213955, 1784409213955, NULL, NULL, NULL, NULL, NULL, 'CHAPA', 'CORTE,DOBRA', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (96, 'AD1003-PL2', 'CORTE PLASMA LATERAL ESQUERDA', NULL, 3, 1784409213956, 1784409213956, NULL, NULL, NULL, NULL, NULL, 'CHAPA', 'CORTE,DOBRA', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (97, 'AD1003-TB1', 'TUBO SUPORTE PRINCIPAL — RETO', '40 × 40 × 3 mm · comp. 490 mm', 2, 1784409213957, 1784409213957, NULL, 490, 3, 40, 40, 'TUBO', 'CORTE', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (98, 'AD1003-REF', 'REFORÇO', '75 × 3 mm · comp. 220 mm', 5, 1784409213958, 1784409213958, NULL, 220, 3, 75, NULL, 'REFORCO', 'CORTE,FURACAO,DOBRA', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (99, 'AD1003-BC', 'BARRA CHATA', '38 × 8 mm · comp. 255 mm', 5, 1784409213959, 1784409213959, NULL, 255, 8, 38, NULL, 'BARRA_CHATA', 'CORTE,DOBRA', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (100, 'AD1003-CT1', 'CANTONEIRA 1', '25 × 6.35 mm · comp. 185 mm', 5, 1784409213960, 1784409213960, NULL, 185, 6.35, 25, NULL, 'CANTONEIRA', 'CORTE', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (101, 'AD1003-CT2', 'CANTONEIRA 2', '25 × 6.35 mm · comp. 70 mm', 5, 1784409213961, 1784409213961, NULL, 70, 6.35, 25, NULL, 'CANTONEIRA', 'CORTE', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (102, 'AD1003-CB1', 'CABEÇA REMOVÍVEL', '60 × 60 × 3.75 mm · comp. 145 mm', 4, 1784409213961, 1784479095660, NULL, 145, 3.75, 60, 60, 'PONTEIRA', 'CORTE', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (103, 'AD1004-PL1-PL2', 'CORTE PLASMA BILATERAL', NULL, 3, 1784409213963, 1784409213963, NULL, NULL, NULL, NULL, NULL, 'CHAPA', 'CORTE,DOBRA', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (104, 'AD1004-TB1', 'TUBO SUPORTE PRINCIPAL — RETO', '40 × 40 × 3 mm · comp. 905 mm', 2, 1784409213964, 1784409213964, NULL, 905, 3, 40, 40, 'TUBO', 'CORTE', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (105, 'AD1004-TB2', 'TUBO MENOR — RETO', '40 × 40 × 3 mm · comp. 190 mm', 2, 1784409213965, 1784409213965, NULL, 190, 3, 40, 40, 'TUBO', 'CORTE', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (106, 'AD1004-CB', 'PONTEIRA REM.', '60 × 60 × 3.75 mm · comp. 165 mm', 4, 1784409213966, 1784479095664, NULL, 165, 3.75, 60, 60, 'PONTEIRA', 'CORTE', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (107, 'AD1004-BC1', 'BARRA CHATA 1', '38 × 8 mm · comp. 290 mm', 5, 1784409213967, 1784409213967, NULL, 290, 8, 38, NULL, 'BARRA_CHATA', 'CORTE,CORTE_GRAU', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (108, 'AD1004-BC2', 'BARRA CHATA 2', '38 × 8 mm · comp. 125 mm', 5, 1784409213968, 1784409213968, NULL, 125, 8, 38, NULL, 'BARRA_CHATA', 'CORTE,FURACAO,DOBRA', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (109, 'AD1004-BC3', 'BARRA CHATA 3', '38 × 8 mm · comp. 290 mm', 5, 1784409213969, 1784409213969, NULL, 290, 8, 38, NULL, 'BARRA_CHATA', 'CORTE,DOBRA,CORTE_GRAU', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (110, 'AD1004-CT1', 'CANTONEIRA 1', '25 × 6.35 mm · comp. 70 mm', 5, 1784409213969, 1784409213969, NULL, 70, 6.35, 25, NULL, 'CANTONEIRA', 'CORTE', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (111, 'AD1005-PL', 'CORTE PLASMA BILATERAL', NULL, 3, 1784409213971, 1784409213971, NULL, NULL, NULL, NULL, NULL, 'CHAPA', 'CORTE,DOBRA', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (112, 'AD1005-TB', 'TUBO SUPORTE PRINCIPAL — RETO', '40 × 40 × 3 mm · comp. 375 mm', 2, 1784409213971, 1784409213971, NULL, 375, 3, 40, 40, 'TUBO', 'CORTE,DOBRA', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (113, 'AD1005-CB', 'PONTEIRA REM.', '60 × 60 × 3.75 mm · comp. 190 mm', 4, 1784409213972, 1784479095667, NULL, 190, 3.75, 60, 60, 'PONTEIRA', 'CORTE', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (114, 'AD1005-BC1', 'BARRA CHATA 1', '100 × 8 mm · comp. 130 mm', 5, 1784409213973, 1784409213973, NULL, 130, 8, 100, NULL, 'BARRA_CHATA', 'CORTE,DOBRA', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (115, 'AD1005-BC2', 'BARRA CHATA 2', '50 × 8 mm · comp. 125 mm', 5, 1784409213974, 1784409213974, NULL, 125, 8, 50, NULL, 'BARRA_CHATA', 'CORTE,FURACAO,DOBRA', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (116, 'AD1005-BC3', 'BARRA CHATA 3', '17 × 6.3 mm · comp. 100 mm', 5, 1784409213974, 1784409213974, NULL, 100, 6.3, 17, NULL, 'BARRA_CHATA', 'CORTE', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (117, 'AD1006-PL1-PL2', 'CORTE PLASMA BILATERAL', NULL, 3, 1784409213976, 1784409213976, NULL, NULL, NULL, NULL, NULL, 'CHAPA', 'CORTE,DOBRA', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (118, 'AD1006-TB', 'TUBO SUPORTE PRINCIPAL — RETO', '40 × 40 × 3 mm · comp. 640 mm', 2, 1784409213977, 1784409213977, NULL, 640, 3, 40, 40, 'TUBO', 'CORTE,DOBRA', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (119, 'AD1006-CB', 'CABEÇA REMOVÍVEL', '60 × 60 × 3.75 mm · comp. 195 mm', 4, 1784409213977, 1784479095670, NULL, 195, 3.75, 60, 60, 'PONTEIRA', 'CORTE', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (120, 'AD1006-BC', 'BARRA CHATA', '50 × 8 mm · comp. 105 mm', 5, 1784409213978, 1784409213978, NULL, 105, 8, 50, NULL, 'BARRA_CHATA', 'CORTE,FURACAO,DOBRA', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (121, 'AD1006-CANT', 'CANTONEIRA', '25 × 6.35 mm · comp. 80 mm', 5, 1784409213979, 1784409213979, NULL, 80, 6.35, 25, NULL, 'CANTONEIRA', 'CORTE', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (122, 'AD1007-TB', 'TUBO SUPORTE PRINCIPAL — RETO', '40 × 40 × 3 mm · comp. 940 mm', 2, 1784409213980, 1784409213980, NULL, 940, 3, 40, 40, 'TUBO', 'CORTE,DOBRA', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (123, 'AD1007-CB', 'PONTEIRA REM.', '60 × 60 × 3.75 mm · comp. 155 mm', 4, 1784409213981, 1784479095673, NULL, 155, 3.75, 60, 60, 'PONTEIRA', 'CORTE', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (124, 'AD1007-BC1', 'BARRA CHATA 100 x 16', '16 × 6.35 mm · comp. 100 mm', 5, 1784409213982, 1784409213982, NULL, 100, 6.35, 16, NULL, 'BARRA_CHATA', 'CORTE', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (125, 'AD1007-BC2', 'BARRA CHATA 120 x 38', '38 × 6.35 mm · comp. 120 mm', 5, 1784409213983, 1784409213983, NULL, 120, 6.35, 38, NULL, 'BARRA_CHATA', 'CORTE,FURACAO,DOBRA', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (126, 'AD1007-PL1', 'PLASMA LATERAL DIREITO', NULL, 3, 1784409213983, 1784409213983, NULL, NULL, NULL, NULL, NULL, 'CHAPA', 'CORTE,DOBRA', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (127, 'AD1007-PL2', 'PLASMA LATERAL ESQUERDO', NULL, 3, 1784409213984, 1784409213984, NULL, NULL, NULL, NULL, NULL, 'CHAPA', 'CORTE,DOBRA', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (128, 'AD1007-BC3', 'BARRA CHATA REFORÇO', '100 × 8 mm · comp. 205 mm', 5, 1784409213985, 1784409213985, NULL, 205, 8, 100, NULL, 'BARRA_CHATA', 'CORTE', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (129, 'AD1008-TB', 'TUBO SUPORTE PRINCIPAL — RETO', '40 × 40 × 3 mm · comp. 900 mm', 2, 1784409213986, 1784409213986, NULL, 900, 3, 40, 40, 'TUBO', 'CORTE,DOBRA', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (130, 'AD1008-CB', 'PONTEIRA REM.', '60 × 60 × 3.75 mm · comp. 310 mm', 4, 1784409213987, 1784479095676, NULL, 310, 3.75, 60, 60, 'PONTEIRA', 'CORTE', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (131, 'AD1008-BC', 'BARRA CHATA', '38 × 6.35 mm · comp. 170 mm', 5, 1784409213988, 1784409213988, NULL, 170, 6.35, 38, NULL, 'BARRA_CHATA', 'CORTE,FURACAO,DOBRA', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (132, 'AD1008-RCB', 'REFORÇO CABEÇA', '75 × 3 mm · comp. 100 mm', 5, 1784409213989, 1784409213989, NULL, 100, 3, 75, NULL, 'REFORCO', 'CORTE', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (133, 'AD1008-PL1', 'PLASMA LATERAL DIREITO', NULL, 3, 1784409213989, 1784409213989, NULL, NULL, NULL, NULL, NULL, 'CHAPA', 'CORTE,DOBRA', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (134, 'AD1008-PL2', 'PLASMA LATERAL ESQUERDO', NULL, 3, 1784409213990, 1784409213990, NULL, NULL, NULL, NULL, NULL, 'CHAPA', 'CORTE,DOBRA', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (135, 'AD1009-TB', 'TUBO SUPORTE PRINCIPAL — RETO', '40 × 40 × 3 mm · comp. 770 mm', 2, 1784409213992, 1784409213992, NULL, 770, 3, 40, 40, 'TUBO', 'CORTE,DOBRA', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (136, 'AD1009-CB', 'PONTEIRA REM.', '60 × 60 × 3.75 mm · comp. 155 mm', 4, 1784409213993, 1784479095679, NULL, 155, 3.75, 60, 60, 'PONTEIRA', 'CORTE', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (137, 'AD1009-BC1', 'BARRA CHATA 160 x 25', '25 × 4.75 mm · comp. 160 mm', 5, 1784409213994, 1784409213994, NULL, 160, 4.75, 25, NULL, 'BARRA_CHATA', 'CORTE', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (138, 'AD1009-BC2', 'BARRA CHATA 130 x 50', '50 × 8 mm · comp. 130 mm', 5, 1784409213995, 1784409213995, NULL, 130, 8, 50, NULL, 'BARRA_CHATA', 'CORTE,FURACAO,DOBRA', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (139, 'AD1009-PL1', 'CORTE PLASMA LATERAL', NULL, 3, 1784409213996, 1784409213996, NULL, NULL, NULL, NULL, NULL, 'CHAPA', 'CORTE,DOBRA', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (140, 'AD1009-PL2', 'CORTE PLASMA BILATERAL', NULL, 3, 1784409213996, 1784409213996, NULL, NULL, NULL, NULL, NULL, 'CHAPA', 'CORTE', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (141, 'AD1009-PL3', 'CORTE PLASMA LATERAL', NULL, 3, 1784409213997, 1784409213997, NULL, NULL, NULL, NULL, NULL, 'CHAPA', 'CORTE,DOBRA', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (142, 'AD1009-BC3', 'BARRA CHATA REFORÇO', '100 × 8 mm · comp. 210 mm', 5, 1784409213998, 1784409213998, NULL, 210, 8, 100, NULL, 'BARRA_CHATA', 'CORTE,DOBRA', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (143, 'AD1010-TB', 'TUBO SUPORTE PRINCIPAL', '40 × 40 × 3 mm · comp. 795 mm', 2, 1784409213999, 1784409213999, NULL, 795, 3, 40, 40, 'TUBO', 'CORTE,DOBRA', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (144, 'AD1010-CB', 'PONTEIRA REM.', '60 × 60 × 3.75 mm · comp. 135 mm', 4, 1784409214000, 1784479095682, NULL, 135, 3.75, 60, 60, 'PONTEIRA', 'CORTE', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (145, 'AD1010-BC1', 'BARRA CHATA 1', '38 × 8 mm · comp. 245 mm', 5, 1784409214001, 1784409214001, NULL, 245, 8, 38, NULL, 'BARRA_CHATA', 'CORTE,FURACAO,DOBRA,CORTE_GRAU', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (146, 'AD1010-BC2', 'BARRA CHATA 2', '38 × 8 mm · comp. 245 mm', 5, 1784409214002, 1784409214002, NULL, 245, 8, 38, NULL, 'BARRA_CHATA', 'CORTE,FURACAO,DOBRA,CORTE_GRAU', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (147, 'AD1010-BC3', 'BARRA CHATA 3', '15 × 4.75 mm · comp. 100 mm', 5, 1784409214002, 1784409214002, NULL, 100, 4.75, 15, NULL, 'BARRA_CHATA', 'CORTE', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (148, 'AD1010-BC', 'BARRA CHATA ACESSÓRIO', '38 × 8 mm · comp. 130 mm', 5, 1784409214003, 1784409214003, NULL, 130, 8, 38, NULL, 'BARRA_CHATA', 'CORTE,FURACAO', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (149, 'AD1010-PL1', 'CORTE PLASMA BILATERAL', NULL, 3, 1784409214004, 1784409214004, NULL, NULL, NULL, NULL, NULL, 'CHAPA', 'CORTE,DOBRA', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (150, 'AD1010-PL2', 'CORTE PLASMA CENTRAL', NULL, 3, 1784409214004, 1784409214004, NULL, NULL, NULL, NULL, NULL, 'CHAPA', 'CORTE', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (151, 'AD1010-PL3', 'CORTE PLASMA BILATERAL', NULL, 3, 1784409214005, 1784409214005, NULL, NULL, NULL, NULL, NULL, 'CHAPA', 'CORTE', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (152, 'FT4000-TUBO-1', 'Tubo 1000x40x3mm', NULL, 2, 1784582640530, 1784582640530, NULL, 1000, 3, 40, NULL, 'TUBO', 'CORTE', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (153, 'FT4000-BARRA_CHATA-2', 'Barra Chata 125x38x6.35mm [Fura, Bate]', NULL, 5, 1784582640535, 1784582640535, NULL, 125, 6.35, 38, NULL, 'BARRA_CHATA', 'CORTE,FURACAO,BATIDA', NULL);
INSERT OR IGNORE INTO "Peca" ("id", "codigo", "nome", "medida", "setorId", "createdAt", "updatedAt", "imagemUrl", "comprimentoMm", "espessuraMm", "medidaA", "medidaB", "tipoMaterial", "processos", "observacao") VALUES (154, 'BM1001-TB', 'TUBO 1400', '1400', 2, 1784583784778, 1784583784778, NULL, NULL, NULL, 40, 3, 'TUBO', NULL, NULL);
INSERT OR IGNORE INTO "Modelo" ("id", "codigo", "curva", "tipo", "createdAt", "updatedAt", "tamanhoPonteira", "estoqueMinimo", "imagemUrl", "nome") VALUES (15, 'AD1001', 'C', 'FIXO', 1784409213940, 1784583921224, NULL, NULL, NULL, 'Engate Fixo Audi A3 Sedan 2012 até 2019');
INSERT OR IGNORE INTO "Modelo" ("id", "codigo", "curva", "tipo", "createdAt", "updatedAt", "tamanhoPonteira", "estoqueMinimo", "imagemUrl", "nome") VALUES (16, 'AD1002N', 'C', 'FIXO', 1784409213948, 1784409213948, NULL, NULL, NULL, 'Engate Fixo Audi Q3 12-19');
INSERT OR IGNORE INTO "Modelo" ("id", "codigo", "curva", "tipo", "createdAt", "updatedAt", "tamanhoPonteira", "estoqueMinimo", "imagemUrl", "nome") VALUES (17, 'AD1003', 'C', 'REMOVIVEL', 1784409213955, 1784409213955, NULL, NULL, NULL, 'Engate Removível Audi A1 2001 até 2019');
INSERT OR IGNORE INTO "Modelo" ("id", "codigo", "curva", "tipo", "createdAt", "updatedAt", "tamanhoPonteira", "estoqueMinimo", "imagemUrl", "nome") VALUES (18, 'AD1004', 'C', 'REMOVIVEL', 1784409213963, 1784409213963, NULL, NULL, NULL, 'Engate Removível Audi Q5 2016 até 2022');
INSERT OR IGNORE INTO "Modelo" ("id", "codigo", "curva", "tipo", "createdAt", "updatedAt", "tamanhoPonteira", "estoqueMinimo", "imagemUrl", "nome") VALUES (19, 'AD1005', 'C', 'REMOVIVEL', 1784409213970, 1784409213970, NULL, NULL, NULL, 'Engate Removível Audi Q5 2012');
INSERT OR IGNORE INTO "Modelo" ("id", "codigo", "curva", "tipo", "createdAt", "updatedAt", "tamanhoPonteira", "estoqueMinimo", "imagemUrl", "nome") VALUES (20, 'AD1006', 'C', 'REMOVIVEL', 1784409213976, 1784409213976, NULL, NULL, NULL, 'Engate Removível Audi A4 2016 até 2019');
INSERT OR IGNORE INTO "Modelo" ("id", "codigo", "curva", "tipo", "createdAt", "updatedAt", "tamanhoPonteira", "estoqueMinimo", "imagemUrl", "nome") VALUES (21, 'AD1007', 'C', 'REMOVIVEL', 1784409213980, 1784409213980, NULL, NULL, NULL, 'Engate Removível Audi Q3 2020-2024');
INSERT OR IGNORE INTO "Modelo" ("id", "codigo", "curva", "tipo", "createdAt", "updatedAt", "tamanhoPonteira", "estoqueMinimo", "imagemUrl", "nome") VALUES (22, 'AD1008', 'C', 'REMOVIVEL', 1784409213986, 1784409213986, NULL, NULL, NULL, 'Engate Removível Audi Q8 E-Tron Sportback 21-24');
INSERT OR IGNORE INTO "Modelo" ("id", "codigo", "curva", "tipo", "createdAt", "updatedAt", "tamanhoPonteira", "estoqueMinimo", "imagemUrl", "nome") VALUES (23, 'AD1009', 'C', 'REMOVIVEL', 1784409213991, 1784409213991, NULL, NULL, NULL, 'Engate Removível Audi Q7 2020-2024');
INSERT OR IGNORE INTO "Modelo" ("id", "codigo", "curva", "tipo", "createdAt", "updatedAt", "tamanhoPonteira", "estoqueMinimo", "imagemUrl", "nome") VALUES (24, 'AD1010', 'C', 'REMOVIVEL', 1784409213999, 1784409213999, NULL, NULL, NULL, 'Audi A5 2011-2017');
INSERT OR IGNORE INTO "Modelo" ("id", "codigo", "curva", "tipo", "createdAt", "updatedAt", "tamanhoPonteira", "estoqueMinimo", "imagemUrl", "nome") VALUES (25, 'FT4000', 'A', 'FIXO', 1784582640527, 1784582640527, NULL, NULL, NULL, 'ENGATE FIAT');
INSERT OR IGNORE INTO "OP" ("id", "numeroSequencia", "modeloId", "quantidade", "status", "dataLiberacao", "createdAt", "updatedAt", "lote", "previsaoEntrega") VALUES (5, 0, 15, 10, 'ABERTA', 1784409296493, 1784409296493, 1784494355926, '1', NULL);
INSERT OR IGNORE INTO "OP" ("id", "numeroSequencia", "modeloId", "quantidade", "status", "dataLiberacao", "createdAt", "updatedAt", "lote", "previsaoEntrega") VALUES (6, 1, 16, 12, 'ABERTA', 1784409301676, 1784409301676, 1784494355935, '2', NULL);
INSERT OR IGNORE INTO "OP" ("id", "numeroSequencia", "modeloId", "quantidade", "status", "dataLiberacao", "createdAt", "updatedAt", "lote", "previsaoEntrega") VALUES (7, 2, 17, 15, 'ABERTA', 1784409307177, 1784409307177, 1784494355939, '3', NULL);
INSERT OR IGNORE INTO "OP" ("id", "numeroSequencia", "modeloId", "quantidade", "status", "dataLiberacao", "createdAt", "updatedAt", "lote", "previsaoEntrega") VALUES (8, 3, 18, 20, 'ABERTA', 1784409311721, 1784409311721, 1784494355943, '4', NULL);
INSERT OR IGNORE INTO "OP" ("id", "numeroSequencia", "modeloId", "quantidade", "status", "dataLiberacao", "createdAt", "updatedAt", "lote", "previsaoEntrega") VALUES (9, 4, 19, 20, 'ABERTA', 1784409316377, 1784409316377, 1784494355947, '5', NULL);
INSERT OR IGNORE INTO "OP" ("id", "numeroSequencia", "modeloId", "quantidade", "status", "dataLiberacao", "createdAt", "updatedAt", "lote", "previsaoEntrega") VALUES (10, 5, 15, 12, 'ABERTA', 1784582498195, 1784582498195, 1784582498195, '123', NULL);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (106, 15, 2, 1);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (107, 15, 3, 3);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (108, 15, 5, 4);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (109, 15, 8, 5);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (110, 15, 9, 6);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (111, 15, 1, 7);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (112, 15, 7, 8);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (113, 15, 6, 9);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (114, 16, 2, 1);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (115, 16, 3, 3);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (116, 16, 5, 4);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (117, 16, 8, 5);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (118, 16, 9, 6);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (119, 16, 1, 7);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (120, 16, 7, 8);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (121, 16, 6, 9);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (122, 17, 2, 1);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (123, 17, 3, 3);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (124, 17, 5, 4);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (125, 17, 8, 5);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (126, 17, 9, 6);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (127, 17, 1, 7);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (128, 17, 7, 8);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (129, 17, 6, 9);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (130, 18, 2, 1);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (131, 18, 3, 3);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (132, 18, 5, 4);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (133, 18, 8, 5);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (134, 18, 9, 6);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (135, 18, 1, 7);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (136, 18, 7, 8);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (137, 18, 6, 9);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (138, 19, 2, 1);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (139, 19, 3, 3);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (140, 19, 5, 4);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (141, 19, 8, 5);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (142, 19, 9, 6);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (143, 19, 1, 7);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (144, 19, 7, 8);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (145, 19, 6, 9);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (146, 20, 2, 1);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (147, 20, 3, 3);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (148, 20, 5, 4);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (149, 20, 8, 5);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (150, 20, 9, 6);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (151, 20, 1, 7);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (152, 20, 7, 8);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (153, 20, 6, 9);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (154, 21, 2, 1);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (155, 21, 3, 3);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (156, 21, 5, 4);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (157, 21, 8, 5);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (158, 21, 9, 6);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (159, 21, 1, 7);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (160, 21, 7, 8);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (161, 21, 6, 9);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (162, 22, 2, 1);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (163, 22, 3, 3);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (164, 22, 5, 4);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (165, 22, 8, 5);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (166, 22, 9, 6);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (167, 22, 1, 7);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (168, 22, 7, 8);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (169, 22, 6, 9);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (170, 23, 2, 1);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (171, 23, 3, 3);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (172, 23, 5, 4);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (173, 23, 8, 5);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (174, 23, 9, 6);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (175, 23, 1, 7);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (176, 23, 7, 8);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (177, 23, 6, 9);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (178, 24, 2, 1);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (179, 24, 3, 3);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (180, 24, 5, 4);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (181, 24, 8, 5);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (182, 24, 9, 6);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (183, 24, 1, 7);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (184, 24, 7, 8);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (185, 24, 6, 9);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (186, 15, 4, 2);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (187, 16, 4, 2);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (188, 17, 4, 2);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (189, 18, 4, 2);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (190, 19, 4, 2);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (191, 20, 4, 2);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (192, 21, 4, 2);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (193, 22, 4, 2);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (194, 23, 4, 2);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (195, 24, 4, 2);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (196, 25, 2, 1);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (197, 25, 5, 2);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (198, 25, 9, 3);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (199, 25, 1, 4);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (200, 25, 7, 5);
INSERT OR IGNORE INTO "ModeloRoteiro" ("id", "modeloId", "setorId", "ordem") VALUES (201, 25, 6, 6);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (83, 15, 83, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (84, 15, 84, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (85, 15, 85, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (86, 15, 86, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (87, 15, 87, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (88, 16, 88, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (89, 16, 89, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (90, 16, 90, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (91, 16, 91, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (92, 16, 92, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (93, 16, 93, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (94, 16, 94, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (95, 17, 95, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (96, 17, 96, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (97, 17, 97, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (98, 17, 98, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (99, 17, 99, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (100, 17, 100, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (101, 17, 101, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (102, 17, 102, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (103, 18, 103, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (104, 18, 104, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (105, 18, 105, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (106, 18, 106, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (107, 18, 107, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (108, 18, 108, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (109, 18, 109, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (110, 18, 110, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (111, 19, 111, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (112, 19, 112, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (113, 19, 113, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (114, 19, 114, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (115, 19, 115, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (116, 19, 116, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (117, 20, 117, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (118, 20, 118, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (119, 20, 119, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (120, 20, 120, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (121, 20, 121, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (122, 21, 122, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (123, 21, 123, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (124, 21, 124, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (125, 21, 125, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (126, 21, 126, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (127, 21, 127, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (128, 21, 128, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (129, 22, 129, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (130, 22, 130, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (131, 22, 131, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (132, 22, 132, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (133, 22, 133, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (134, 22, 134, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (135, 23, 135, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (136, 23, 136, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (137, 23, 137, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (138, 23, 138, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (139, 23, 139, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (140, 23, 140, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (141, 23, 141, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (142, 23, 142, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (143, 24, 143, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (144, 24, 144, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (145, 24, 145, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (146, 24, 146, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (147, 24, 147, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (148, 24, 148, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (149, 24, 149, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (150, 24, 150, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (151, 24, 151, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (152, 25, 152, 1);
INSERT OR IGNORE INTO "ModeloPeca" ("id", "modeloId", "pecaId", "quantidadeNecessaria") VALUES (153, 25, 153, 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (205, 83, 3, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (206, 83, 3, 'DOBRA', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (207, 83, 9, 'AGRUPAR', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (208, 84, 3, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (209, 84, 3, 'DOBRA', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (210, 84, 9, 'AGRUPAR', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (211, 85, 2, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (212, 85, 2, 'DOBRA', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (213, 85, 2, 'CORTE_GRAU', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (214, 85, 9, 'AGRUPAR', 4);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (215, 86, 4, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (216, 86, 8, 'LIXAR', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (217, 87, 8, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (218, 87, 5, 'DOBRA', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (219, 87, 9, 'AGRUPAR', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (220, 88, 3, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (221, 88, 3, 'DOBRA', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (222, 88, 9, 'AGRUPAR', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (223, 89, 3, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (224, 89, 3, 'DOBRA', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (225, 89, 9, 'AGRUPAR', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (226, 90, 3, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (227, 90, 3, 'DOBRA', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (228, 90, 9, 'AGRUPAR', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (229, 91, 3, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (230, 91, 9, 'AGRUPAR', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (231, 92, 2, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (232, 92, 9, 'AGRUPAR', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (233, 93, 4, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (234, 93, 8, 'LIXAR', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (235, 94, 5, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (236, 94, 5, 'DOBRA', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (237, 94, 9, 'AGRUPAR', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (238, 95, 3, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (239, 95, 3, 'DOBRA', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (240, 95, 9, 'AGRUPAR', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (241, 96, 3, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (242, 96, 3, 'DOBRA', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (243, 96, 9, 'AGRUPAR', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (244, 97, 2, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (245, 97, 9, 'AGRUPAR', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (246, 98, 8, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (247, 98, 5, 'DOBRA', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (248, 98, 9, 'AGRUPAR', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (249, 99, 5, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (250, 99, 5, 'DOBRA', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (251, 99, 9, 'AGRUPAR', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (252, 100, 5, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (253, 100, 8, 'DOBRA', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (254, 100, 9, 'AGRUPAR', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (255, 101, 5, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (256, 101, 8, 'DOBRA', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (257, 101, 9, 'AGRUPAR', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (258, 102, 4, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (259, 102, 8, 'LIXAR', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (260, 102, 8, 'SOLDAGEM', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (261, 103, 3, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (262, 103, 3, 'DOBRA', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (263, 103, 9, 'AGRUPAR', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (264, 104, 2, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (265, 104, 9, 'AGRUPAR', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (266, 105, 2, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (267, 105, 9, 'AGRUPAR', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (268, 106, 4, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (269, 106, 8, 'LIXAR', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (270, 106, 8, 'SOLDAGEM', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (271, 107, 5, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (272, 107, 5, 'CORTE_GRAU', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (273, 107, 9, 'AGRUPAR', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (274, 108, 5, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (275, 108, 5, 'FURACAO', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (276, 108, 5, 'DOBRA', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (277, 108, 9, 'AGRUPAR', 4);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (278, 109, 5, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (279, 109, 5, 'DOBRA', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (280, 109, 5, 'CORTE_GRAU', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (281, 109, 9, 'AGRUPAR', 4);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (282, 110, 5, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (283, 110, 8, 'DOBRA', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (284, 110, 9, 'AGRUPAR', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (285, 111, 3, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (286, 111, 3, 'DOBRA', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (287, 111, 9, 'AGRUPAR', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (288, 112, 2, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (289, 112, 2, 'DOBRA', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (290, 112, 9, 'AGRUPAR', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (291, 113, 4, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (292, 113, 8, 'LIXAR', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (293, 113, 8, 'SOLDAGEM', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (294, 114, 5, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (295, 114, 5, 'DOBRA', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (296, 114, 9, 'AGRUPAR', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (297, 115, 5, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (298, 115, 5, 'FURACAO', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (299, 115, 5, 'DOBRA', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (300, 115, 9, 'AGRUPAR', 4);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (301, 116, 5, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (302, 116, 9, 'AGRUPAR', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (303, 117, 3, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (304, 117, 3, 'DOBRA', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (305, 117, 9, 'AGRUPAR', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (306, 118, 2, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (307, 118, 2, 'DOBRA', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (308, 118, 9, 'AGRUPAR', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (309, 119, 4, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (310, 119, 8, 'LIXAR', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (311, 119, 8, 'SOLDAGEM', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (312, 120, 5, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (313, 120, 5, 'FURACAO', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (314, 120, 5, 'DOBRA', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (315, 120, 9, 'AGRUPAR', 4);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (316, 121, 5, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (317, 121, 8, 'DOBRA', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (318, 121, 9, 'AGRUPAR', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (319, 122, 2, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (320, 122, 2, 'DOBRA', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (321, 122, 9, 'AGRUPAR', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (322, 123, 4, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (323, 123, 8, 'LIXAR', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (324, 123, 8, 'SOLDAGEM', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (325, 124, 5, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (326, 124, 9, 'AGRUPAR', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (327, 125, 5, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (328, 125, 5, 'FURACAO', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (329, 125, 5, 'DOBRA', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (330, 125, 9, 'AGRUPAR', 4);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (331, 126, 3, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (332, 126, 3, 'DOBRA', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (333, 126, 9, 'AGRUPAR', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (334, 127, 3, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (335, 127, 3, 'DOBRA', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (336, 127, 9, 'AGRUPAR', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (337, 128, 5, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (338, 128, 9, 'AGRUPAR', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (339, 129, 2, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (340, 129, 2, 'DOBRA', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (341, 129, 9, 'AGRUPAR', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (342, 130, 4, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (343, 130, 8, 'LIXAR', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (344, 130, 8, 'SOLDAGEM', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (345, 131, 5, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (346, 131, 5, 'FURACAO', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (347, 131, 5, 'DOBRA', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (348, 131, 9, 'AGRUPAR', 4);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (349, 132, 8, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (350, 132, 5, 'DOBRA', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (351, 132, 9, 'AGRUPAR', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (352, 133, 3, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (353, 133, 3, 'DOBRA', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (354, 133, 9, 'AGRUPAR', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (355, 134, 3, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (356, 134, 3, 'DOBRA', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (357, 134, 9, 'AGRUPAR', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (358, 135, 2, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (359, 135, 2, 'DOBRA', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (360, 135, 9, 'AGRUPAR', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (361, 136, 4, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (362, 136, 8, 'LIXAR', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (363, 136, 8, 'SOLDAGEM', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (364, 137, 5, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (365, 137, 9, 'AGRUPAR', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (366, 138, 5, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (367, 138, 5, 'FURACAO', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (368, 138, 5, 'DOBRA', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (369, 138, 9, 'AGRUPAR', 4);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (370, 139, 3, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (371, 139, 3, 'DOBRA', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (372, 139, 9, 'AGRUPAR', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (373, 140, 3, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (374, 140, 9, 'AGRUPAR', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (375, 141, 3, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (376, 141, 3, 'DOBRA', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (377, 141, 9, 'AGRUPAR', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (378, 142, 5, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (379, 142, 5, 'DOBRA', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (380, 142, 9, 'AGRUPAR', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (381, 143, 2, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (382, 143, 2, 'DOBRA', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (383, 143, 9, 'AGRUPAR', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (384, 144, 4, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (385, 144, 8, 'LIXAR', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (386, 144, 8, 'SOLDAGEM', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (387, 145, 5, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (388, 145, 5, 'FURACAO', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (389, 145, 5, 'DOBRA', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (390, 145, 5, 'CORTE_GRAU', 4);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (391, 145, 9, 'AGRUPAR', 5);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (392, 146, 5, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (393, 146, 5, 'FURACAO', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (394, 146, 5, 'DOBRA', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (395, 146, 5, 'CORTE_GRAU', 4);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (396, 146, 9, 'AGRUPAR', 5);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (397, 147, 5, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (398, 147, 9, 'AGRUPAR', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (399, 148, 5, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (400, 148, 5, 'FURACAO', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (401, 148, 9, 'AGRUPAR', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (402, 149, 3, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (403, 149, 3, 'DOBRA', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (404, 149, 9, 'AGRUPAR', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (405, 150, 3, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (406, 150, 9, 'AGRUPAR', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (407, 151, 3, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (408, 151, 9, 'AGRUPAR', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (409, 86, 8, 'SOLDAGEM', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (410, 86, 9, 'AGRUPAR', 4);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (411, 93, 8, 'SOLDAGEM', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (412, 93, 9, 'AGRUPAR', 4);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (413, 102, 9, 'AGRUPAR', 4);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (414, 106, 9, 'AGRUPAR', 4);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (415, 113, 9, 'AGRUPAR', 4);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (416, 119, 9, 'AGRUPAR', 4);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (417, 123, 9, 'AGRUPAR', 4);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (418, 130, 9, 'AGRUPAR', 4);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (419, 136, 9, 'AGRUPAR', 4);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (420, 144, 9, 'AGRUPAR', 4);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (421, 152, 2, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (422, 152, 9, 'AGRUPAR', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (423, 153, 5, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (424, 153, 5, 'FURACAO', 2);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (425, 153, 5, 'BATIDA', 3);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (426, 153, 9, 'AGRUPAR', 4);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (427, 154, 2, 'CORTE', 1);
INSERT OR IGNORE INTO "PecaRoteiro" ("id", "pecaId", "setorId", "processo", "ordem") VALUES (428, 154, 9, 'AGRUPAR', 2);
INSERT OR IGNORE INTO "Apontamento" ("id", "opId", "setorId", "usuario", "quantidadeBoa", "quantidadeRefugo", "dataHora", "soldador", "bancada", "abastecedor", "quantidadeSoldada", "pecaId", "processo", "roteiroEtapaId", "origem") VALUES (19, 5, 2, 'CARLOS', 10, 0, 1784409559919, NULL, NULL, NULL, 0, 85, 'CORTE', NULL, 'OPERADOR');
INSERT OR IGNORE INTO "Apontamento" ("id", "opId", "setorId", "usuario", "quantidadeBoa", "quantidadeRefugo", "dataHora", "soldador", "bancada", "abastecedor", "quantidadeSoldada", "pecaId", "processo", "roteiroEtapaId", "origem") VALUES (20, 5, 2, 'ANDRE', 10, 0, 1784412973302, NULL, NULL, NULL, 0, 85, 'DOBRA', NULL, 'OPERADOR');
INSERT OR IGNORE INTO "Apontamento" ("id", "opId", "setorId", "usuario", "quantidadeBoa", "quantidadeRefugo", "dataHora", "soldador", "bancada", "abastecedor", "quantidadeSoldada", "pecaId", "processo", "roteiroEtapaId", "origem") VALUES (21, 5, 3, 'ANDRE', 5, 0, 1784412998201, NULL, NULL, NULL, 0, 83, 'CORTE', NULL, 'OPERADOR');
INSERT OR IGNORE INTO "Apontamento" ("id", "opId", "setorId", "usuario", "quantidadeBoa", "quantidadeRefugo", "dataHora", "soldador", "bancada", "abastecedor", "quantidadeSoldada", "pecaId", "processo", "roteiroEtapaId", "origem") VALUES (22, 5, 5, 'ANDRE', 5, 0, 1784413002751, NULL, NULL, NULL, 0, 87, 'CORTE', NULL, 'OPERADOR');
INSERT OR IGNORE INTO "Apontamento" ("id", "opId", "setorId", "usuario", "quantidadeBoa", "quantidadeRefugo", "dataHora", "soldador", "bancada", "abastecedor", "quantidadeSoldada", "pecaId", "processo", "roteiroEtapaId", "origem") VALUES (23, 5, 4, 'ANDRE', 10, 0, 1784413008069, NULL, NULL, NULL, 0, 86, 'CORTE', NULL, 'OPERADOR');
INSERT OR IGNORE INTO "Apontamento" ("id", "opId", "setorId", "usuario", "quantidadeBoa", "quantidadeRefugo", "dataHora", "soldador", "bancada", "abastecedor", "quantidadeSoldada", "pecaId", "processo", "roteiroEtapaId", "origem") VALUES (24, 5, 3, 'CAIO', 10, 0, 1784413064480, NULL, NULL, NULL, 0, 84, 'CORTE', NULL, 'OPERADOR');
INSERT OR IGNORE INTO "Apontamento" ("id", "opId", "setorId", "usuario", "quantidadeBoa", "quantidadeRefugo", "dataHora", "soldador", "bancada", "abastecedor", "quantidadeSoldada", "pecaId", "processo", "roteiroEtapaId", "origem") VALUES (25, 8, 2, 'JOAO', 7, 0, 1784457699148, NULL, NULL, NULL, 0, 104, 'CORTE', 264, 'OPERADOR');
INSERT OR IGNORE INTO "Apontamento" ("id", "opId", "setorId", "usuario", "quantidadeBoa", "quantidadeRefugo", "dataHora", "soldador", "bancada", "abastecedor", "quantidadeSoldada", "pecaId", "processo", "roteiroEtapaId", "origem") VALUES (26, 5, 8, 'ALAN', 10, 0, 1784457847238, NULL, NULL, NULL, 0, 87, 'CORTE', 217, 'OPERADOR');
INSERT OR IGNORE INTO "Apontamento" ("id", "opId", "setorId", "usuario", "quantidadeBoa", "quantidadeRefugo", "dataHora", "soldador", "bancada", "abastecedor", "quantidadeSoldada", "pecaId", "processo", "roteiroEtapaId", "origem") VALUES (27, 6, 4, 'ALAN', 12, 0, 1784457851470, NULL, NULL, NULL, 0, 93, 'CORTE', 233, 'OPERADOR');
INSERT OR IGNORE INTO "Apontamento" ("id", "opId", "setorId", "usuario", "quantidadeBoa", "quantidadeRefugo", "dataHora", "soldador", "bancada", "abastecedor", "quantidadeSoldada", "pecaId", "processo", "roteiroEtapaId", "origem") VALUES (28, 6, 2, 'ALAN', 12, 0, 1784457863326, NULL, NULL, NULL, 0, 92, 'CORTE', 231, 'OPERADOR');
INSERT OR IGNORE INTO "Apontamento" ("id", "opId", "setorId", "usuario", "quantidadeBoa", "quantidadeRefugo", "dataHora", "soldador", "bancada", "abastecedor", "quantidadeSoldada", "pecaId", "processo", "roteiroEtapaId", "origem") VALUES (29, 5, 2, 'ALAN', 7, 0, 1784457869414, NULL, NULL, NULL, 0, 85, 'CORTE_GRAU', 213, 'OPERADOR');
INSERT OR IGNORE INTO "Apontamento" ("id", "opId", "setorId", "usuario", "quantidadeBoa", "quantidadeRefugo", "dataHora", "soldador", "bancada", "abastecedor", "quantidadeSoldada", "pecaId", "processo", "roteiroEtapaId", "origem") VALUES (30, 5, 2, 'CARLOS', 3, 0, 1784459837448, NULL, NULL, NULL, 0, 85, 'CORTE_GRAU', 213, 'OPERADOR');
INSERT OR IGNORE INTO "Apontamento" ("id", "opId", "setorId", "usuario", "quantidadeBoa", "quantidadeRefugo", "dataHora", "soldador", "bancada", "abastecedor", "quantidadeSoldada", "pecaId", "processo", "roteiroEtapaId", "origem") VALUES (31, 7, 2, 'JOAO', 15, 0, 1784459842179, NULL, NULL, NULL, 0, 97, 'CORTE', 244, 'OPERADOR');
INSERT OR IGNORE INTO "Apontamento" ("id", "opId", "setorId", "usuario", "quantidadeBoa", "quantidadeRefugo", "dataHora", "soldador", "bancada", "abastecedor", "quantidadeSoldada", "pecaId", "processo", "roteiroEtapaId", "origem") VALUES (32, 5, 3, 'GILBERTO', 5, 0, 1784459854173, NULL, NULL, NULL, 0, 83, 'CORTE', 205, 'OPERADOR');
INSERT OR IGNORE INTO "Apontamento" ("id", "opId", "setorId", "usuario", "quantidadeBoa", "quantidadeRefugo", "dataHora", "soldador", "bancada", "abastecedor", "quantidadeSoldada", "pecaId", "processo", "roteiroEtapaId", "origem") VALUES (33, 5, 3, 'GILBERTO', 10, 0, 1784459858775, NULL, NULL, NULL, 0, 83, 'DOBRA', 206, 'OPERADOR');
INSERT OR IGNORE INTO "Apontamento" ("id", "opId", "setorId", "usuario", "quantidadeBoa", "quantidadeRefugo", "dataHora", "soldador", "bancada", "abastecedor", "quantidadeSoldada", "pecaId", "processo", "roteiroEtapaId", "origem") VALUES (34, 5, 3, 'GILBERTO', 10, 0, 1784459864893, NULL, NULL, NULL, 0, 84, 'DOBRA', 209, 'OPERADOR');
INSERT OR IGNORE INTO "Apontamento" ("id", "opId", "setorId", "usuario", "quantidadeBoa", "quantidadeRefugo", "dataHora", "soldador", "bancada", "abastecedor", "quantidadeSoldada", "pecaId", "processo", "roteiroEtapaId", "origem") VALUES (35, 5, 5, 'GILBERTO', 10, 0, 1784459870942, NULL, NULL, NULL, 0, 87, 'DOBRA', 218, 'OPERADOR');
INSERT OR IGNORE INTO "Apontamento" ("id", "opId", "setorId", "usuario", "quantidadeBoa", "quantidadeRefugo", "dataHora", "soldador", "bancada", "abastecedor", "quantidadeSoldada", "pecaId", "processo", "roteiroEtapaId", "origem") VALUES (36, 7, 8, 'RODRIGO', 15, 0, 1784460124263, NULL, NULL, NULL, 0, 98, 'CORTE', 246, 'OPERADOR');
INSERT OR IGNORE INTO "Apontamento" ("id", "opId", "setorId", "usuario", "quantidadeBoa", "quantidadeRefugo", "dataHora", "soldador", "bancada", "abastecedor", "quantidadeSoldada", "pecaId", "processo", "roteiroEtapaId", "origem") VALUES (37, 7, 5, 'RENATO', 15, 0, 1784460397035, NULL, NULL, NULL, 0, 98, 'DOBRA', 247, 'OPERADOR');
INSERT OR IGNORE INTO "Apontamento" ("id", "opId", "setorId", "usuario", "quantidadeBoa", "quantidadeRefugo", "dataHora", "soldador", "bancada", "abastecedor", "quantidadeSoldada", "pecaId", "processo", "roteiroEtapaId", "origem") VALUES (38, 5, 1, 'ANTONIO', 8, 0, 1784473200000, 'ANTONIO', 'BOX1', 'MARIO', 0, NULL, NULL, NULL, 'OPERADOR');
INSERT OR IGNORE INTO "Apontamento" ("id", "opId", "setorId", "usuario", "quantidadeBoa", "quantidadeRefugo", "dataHora", "soldador", "bancada", "abastecedor", "quantidadeSoldada", "pecaId", "processo", "roteiroEtapaId", "origem") VALUES (39, 5, 1, 'ANTONIO', 3, 0, 1784461173772, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'OPERADOR');
INSERT OR IGNORE INTO "Apontamento" ("id", "opId", "setorId", "usuario", "quantidadeBoa", "quantidadeRefugo", "dataHora", "soldador", "bancada", "abastecedor", "quantidadeSoldada", "pecaId", "processo", "roteiroEtapaId", "origem") VALUES (40, 7, 9, 'LUCAS', 7, 0, 1784478993277, NULL, NULL, NULL, 0, 98, 'AGRUPAR', 248, 'OPERADOR');
INSERT OR IGNORE INTO "Apontamento" ("id", "opId", "setorId", "usuario", "quantidadeBoa", "quantidadeRefugo", "dataHora", "soldador", "bancada", "abastecedor", "quantidadeSoldada", "pecaId", "processo", "roteiroEtapaId", "origem") VALUES (41, 7, 5, 'ANA', 5, 0, 1784479151708, NULL, NULL, NULL, 0, 100, 'CORTE', 252, 'OPERADOR');
INSERT OR IGNORE INTO "Apontamento" ("id", "opId", "setorId", "usuario", "quantidadeBoa", "quantidadeRefugo", "dataHora", "soldador", "bancada", "abastecedor", "quantidadeSoldada", "pecaId", "processo", "roteiroEtapaId", "origem") VALUES (42, 5, 8, 'RODRIGO', 10, 0, 1784479682448, NULL, NULL, NULL, 0, 86, 'LIXAR', 216, 'OPERADOR');
INSERT OR IGNORE INTO "Apontamento" ("id", "opId", "setorId", "usuario", "quantidadeBoa", "quantidadeRefugo", "dataHora", "soldador", "bancada", "abastecedor", "quantidadeSoldada", "pecaId", "processo", "roteiroEtapaId", "origem") VALUES (43, 5, 8, 'HUGO', 10, 0, 1784490499904, NULL, NULL, NULL, 0, 86, 'SOLDAGEM', 409, 'OPERADOR');
INSERT OR IGNORE INTO "Apontamento" ("id", "opId", "setorId", "usuario", "quantidadeBoa", "quantidadeRefugo", "dataHora", "soldador", "bancada", "abastecedor", "quantidadeSoldada", "pecaId", "processo", "roteiroEtapaId", "origem") VALUES (44, 6, 8, 'HUGO', 12, 0, 1784490505109, NULL, NULL, NULL, 0, 93, 'LIXAR', 234, 'OPERADOR');
INSERT OR IGNORE INTO "Apontamento" ("id", "opId", "setorId", "usuario", "quantidadeBoa", "quantidadeRefugo", "dataHora", "soldador", "bancada", "abastecedor", "quantidadeSoldada", "pecaId", "processo", "roteiroEtapaId", "origem") VALUES (45, 5, 1, 'MARIO', 2, 0, 1784473200000, 'MARIO', 'BOX1', 'MARIO', 0, NULL, NULL, NULL, 'OPERADOR');
INSERT OR IGNORE INTO "Apontamento" ("id", "opId", "setorId", "usuario", "quantidadeBoa", "quantidadeRefugo", "dataHora", "soldador", "bancada", "abastecedor", "quantidadeSoldada", "pecaId", "processo", "roteiroEtapaId", "origem") VALUES (46, 5, 1, 'ANTONIO', 2, 0, 1784490618634, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'OPERADOR');
INSERT OR IGNORE INTO "Apontamento" ("id", "opId", "setorId", "usuario", "quantidadeBoa", "quantidadeRefugo", "dataHora", "soldador", "bancada", "abastecedor", "quantidadeSoldada", "pecaId", "processo", "roteiroEtapaId", "origem") VALUES (47, 5, 1, 'MARIO', 2, 0, 1784490622231, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'OPERADOR');
INSERT OR IGNORE INTO "Apontamento" ("id", "opId", "setorId", "usuario", "quantidadeBoa", "quantidadeRefugo", "dataHora", "soldador", "bancada", "abastecedor", "quantidadeSoldada", "pecaId", "processo", "roteiroEtapaId", "origem") VALUES (48, 5, 1, 'TIAGO A', 1, 0, 1784490682243, NULL, NULL, NULL, 0, NULL, NULL, NULL, 'OPERADOR');
INSERT OR IGNORE INTO "RecebimentoAgrupamento" ("id", "opId", "setorOrigemId", "categoria", "recebidoPor", "localizacao", "dataHora") VALUES (1, 5, 2, 'SETOR:2', 'mendes', 'PA-C2-N1', 1784459800873);
INSERT OR IGNORE INTO "RecebimentoAgrupamento" ("id", "opId", "setorOrigemId", "categoria", "recebidoPor", "localizacao", "dataHora") VALUES (2, 5, 3, 'SETOR:3', 'mendes', 'PA-C2-N2', 1784460234903);
INSERT OR IGNORE INTO "RecebimentoAgrupamento" ("id", "opId", "setorOrigemId", "categoria", "recebidoPor", "localizacao", "dataHora") VALUES (3, 5, 5, 'SETOR:5', 'mendes', 'PA-C2-N3', 1784460670082);
INSERT OR IGNORE INTO "RecebimentoAgrupamento" ("id", "opId", "setorOrigemId", "categoria", "recebidoPor", "localizacao", "dataHora") VALUES (4, 5, 8, 'PONTEIRA', 'mendes', 'PA-C2-N8', 1784460261070);
INSERT OR IGNORE INTO "RecebimentoAgrupamento" ("id", "opId", "setorOrigemId", "categoria", "recebidoPor", "localizacao", "dataHora") VALUES (6, 5, 4, 'SETOR:4', 'mendes', 'PA-C2-N3', 1784480540441);
INSERT OR IGNORE INTO "RecebimentoAgrupamento" ("id", "opId", "setorOrigemId", "categoria", "recebidoPor", "localizacao", "dataHora") VALUES (7, 5, 5, 'REFORCO', 'tiago', 'n1-pa-c2', 1784490445924);
